version: '3.8'

services:
 web:
  build:
   context: .
  ports:
  - 5000:5000
  volumes:
  - ./:/app
  stop_signal: SIGINT
  environment:
  - MONGODB_CONNSTRING=mongodb://AzureDiamond:hunter2@mongodb
  depends_on: 
  - mongodb

 mongodb:
  image: mongo:5.0
  environment:
   - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
   - MONGO_INITDB_ROOT_PASSWORD=hunter2
  volumes:
  - mongodb:/var/lib/mongodb

secrets:
  db_root_password:
    file: db_root_password.txt

volumes:
  mongodb:
